# Generated by Django 2.2.3 on 2019-08-01 05:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticles',
            name='author',
            field=models.ForeignKey(on_delete='CASCADE', related_name='blog_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
